### ISSUE TITLE
release 1.0 as final?

### ISSUE THREAD

**Issue by ccoenen** [hubotio/generator-hubot#98]
1.0 has been in prerelease for quite some time. Wouldn't it make sense to make the transition?

(feel free to close as invalid, this is not really a problem or an issue)

**Comment by brntbeer** [comment]
@ccoenen i concur! 

I've tested installing Hubot with `yo` after downloading the 1.0 patch (`npm install --g generator-hubot@1.0`) and pushed to Heroku and have it talking in slack now. So things seem fine.

@technicalpickles @bkeepers @bhuga @michaelansel ya'll are listed as maintainers on `npm info generator-hubot`, what are your thoughts on removing 1.0 as pre-release so that this thing gets going?

**Comment by stephenyeargin** [comment]
Came across after generating a new Hubot script package and noticing it was using outdated files (that I then had to go in and clean up). I'm in support of moving this bravely towards Hubot 3.0 for great justice. 😁 :shipit:

**Comment by brntbeer** [comment]
friendly bump towards @technicalpickles @bkeepers @bhuga or @michaelansel on thoughts here

**Comment by stephenyeargin** [comment]
As of [v1.1.0](https://github.com/hubotio/generator-hubot/releases/tag/v1.1.0) it looks like things are back in business. Ran the generator and got `hubot@3.1.1`.
